#include "common.hpp"
#include "gta_util.hpp"
#include "network_recovery_unlocks.h"
#include "natives.hpp"
#include "pointers.hpp"
#include "script.hpp"
#include "../render.h"
#include "../abstract_submenu.h"
#include "../break_option.h"
#include "../toggle_option.h"
#include "../number.h"
#include "../option.h"
#include "../submenu_option.h"
#include "../simple_option.h"
#include "../simple_submenu.h"
#include "../bool_and_number.h"
#include "../submenu_option.h"
#include "../keyboard_option.h"
#include "../submenus.h"
#include "lists.h"
#include "fiber_pool.hpp"
#include "xorstr.h"

namespace recovery
{
	void unlock_all() {
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_XP_FM"), 2165850, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STAM"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STRN"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_LUNG"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_DRIV"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_FLY"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_SHO"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STL"), 100, 0);

		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_12"), -1, 1);

		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMRACEWORLDRECHOLDER"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_ENEMYDRIVEBYKILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_USJS_COMPLETED"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_USJS_FOUND"), 50, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMWINALLRACEMODES"), 1, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMWINEVERYGAMEMODE"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_DB_PLAYER_KILLS"), 1000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_KILLS_PLAYERS"), 1000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMHORDWAVESSURVIVE"), 21, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TDM_MVP"), 60, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_HOLD_UP_SHOPS"), 20, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_RACES_WON"), 101, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_NO_ARMWRESTLING_WINS"), 21, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMATTGANGHQ"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMBBETWIN"), 50000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_WINS"), 51, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMFULLYMODDEDCAR"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_TOTALKILLS"), 500, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_DM_TOTAL_DEATHS"), 412, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TIMES_FINISH_DM_TOP_3"), 36, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PLAYER_HEADSHOTS"), 623, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_WINS"), 63, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TDM_WINS"), 13, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_GTA_RACES_WON"), 12, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_GOLF_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_TG_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_RT_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_CT_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_GRAN_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TENNIS_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TENNIS_MATCHES_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_TDEATHMATCH_WON"), 63, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_RACES_WON"), 101, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_DEATHMATCH_LOST"), 23, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_RACES_LOST"), 36, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_25_KILLS_STICKYBOMBS"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_50_KILLS_GRENADES"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRENADE_ENEMY_KILLS"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_20_KILLS_MELEE"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MOLOTOV_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CMBTPISTOL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PISTOL50_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_APPISTOL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MICROSMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTSMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CRBNRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADVRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CMBTMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PUMP_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SAWNOFF_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_BULLPUP_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTSHTGN_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SNIPERRFL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_HVYSNIPER_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRNLAUNCH_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_RPG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MINIGUNS_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRENADE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SMKGRENADE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_STKYBMB_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MOLOTOV_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_OUTFIT"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_5"), -1, 1);;
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_6"), -1, 1);;
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_OUTFIT"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TORSO"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL2_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_DECL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TORSO"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL2_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_DECL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_0"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_12"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_13"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_14"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_15"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_16"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_17"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_18"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_19"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_21"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_22"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_23"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_24"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_24"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_25"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_26"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_27"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_28"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_29"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_30"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_31"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_32"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_33"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_34"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_35"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_36"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_37"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_38"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_39"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_40"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_13"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
	}
	void unlock_weapons() {
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_25_KILLS_STICKYBOMBS"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_50_KILLS_GRENADES"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRENADE_ENEMY_KILLS"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_20_KILLS_MELEE"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MOLOTOV_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CMBTPISTOL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PISTOL50_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_APPISTOL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MICROSMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTSMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CRBNRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADVRIFLE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CMBTMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTMG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PUMP_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SAWNOFF_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_BULLPUP_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_ASLTSHTGN_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SNIPERRFL_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_HVYSNIPER_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRNLAUNCH_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_RPG_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MINIGUNS_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRENADE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SMKGRENADE_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_STKYBMB_ENEMY_KILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MOLOTOV_ENEMY_KILLS"), 600, 0);
	}
	void unlock_clothing() {
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_HAIR_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_JBIB_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_LEGS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_FEET_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_BERD_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_PROPS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_OUTFIT"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_5"), -1, 1);;
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_HAIR_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_JBIB_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_6"), -1, 1);;
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_LEGS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_FEET_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_BERD_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_PROPS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_OUTFIT"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TORSO"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_SPECIAL2_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_DECL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_AVAILABLE_TEETH_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TORSO"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_SPECIAL2_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_DECL"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CLTHS_ACQUIRED_TEETH_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_0"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_12"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_13"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_14"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_15"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_16"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_17"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_18"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_19"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_21"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_22"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_23"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_24"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_24"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_25"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_26"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_27"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_28"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_29"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_30"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_31"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_32"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_33"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_34"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_35"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_36"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_37"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_38"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_39"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_DLC_APPAREL_ACQUIRED_40"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_13"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_ADMIN_CLOTHES_GV_BS_12"), -1, 1);
	}

	void unlock_tattoo() {
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_1"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_2"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_3"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_4"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_5"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_6"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_7"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_8"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_9"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_10"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_11"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_tattoo_fm_unlocks_12"), -1, 1);
	}
	void unlock_stats() {
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STAM"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STRN"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_LUNG"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_DRIV"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_FLY"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_SHO"), 100, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_SCRIPT_INCREASE_STL"), 100, 0);
	}
	void unlock_snacks() {
		STATS::STAT_SET_INT(rage::joaat("MP0_NO_BOUGHT_YUM_SNACKS"), 99999999, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_NO_BOUGHT_HEALTH_SNACKS"), 99999999, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_NO_BOUGHT_EPIC_SNACKS"), 99999999, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_CIGARETTES_BOUGHT"), 99999999, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_NUMBER_OF_ORANGE_BOUGHT"), 99999999, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_NUMBER_OF_BOURGE_BOUGHT"), 99999999, 0);
	}
	void unlock_lsc() {
		STATS::STAT_SET_INT(rage::joaat("MP0_RACES_WON"), 50, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_1_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_2_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_3_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_4_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_5_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_6_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_CHAR_FM_CARMOD_7_UNLCK"), -1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMRALLYWONDRIVE"), 1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMRALLYWONNAV"), 1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMWINSEARACE"), 1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMWINAIRRACE"), 1, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_NUMBER_TURBO_STARTS_IN_RACE"), 50, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_USJS_COMPLETED"), 50, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_RACES_FASTEST_LAP"), 50, 1);
		STATS::STAT_SET_INT(rage::joaat("MP0_NUMBER_SLIPSTREAMS_IN_RACE"), 100, 1);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMRACEWORLDRECHOLDER"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_ENEMYDRIVEBYKILLS"), 600, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_USJS_COMPLETED"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_USJS_FOUND"), 50, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMWINALLRACEMODES"), 1, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMWINEVERYGAMEMODE"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_DB_PLAYER_KILLS"), 1000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_KILLS_PLAYERS"), 1000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMHORDWAVESSURVIVE"), 21, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_CAR_BOMBS_ENEMY_KILLS"), 25, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TDM_MVP"), 60, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_HOLD_UP_SHOPS"), 20, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_RACES_WON"), 101, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_NO_ARMWRESTLING_WINS"), 21, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMATTGANGHQ"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FMBBETWIN"), 50000, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_WINS"), 51, 0);
		STATS::STAT_SET_BOOL(rage::joaat("MP0_AWD_FMFULLYMODDEDCAR"), 1, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_TOTALKILLS"), 500, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_DM_TOTAL_DEATHS"), 412, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TIMES_FINISH_DM_TOP_3"), 36, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_PLAYER_HEADSHOTS"), 623, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_DM_WINS"), 63, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TDM_WINS"), 13, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_GTA_RACES_WON"), 12, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_GOLF_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_TG_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_RT_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_CT_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_SHOOTRANG_GRAN_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_FM_TENNIS_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TENNIS_MATCHES_WON"), 2, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_TDEATHMATCH_WON"), 63, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_RACES_WON"), 101, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_DEATHMATCH_LOST"), 23, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_MPPLY_TOTAL_RACES_LOST"), 36, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_25_KILLS_STICKYBOMBS"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_50_KILLS_GRENADES"), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_GRENADE_ENEMY_KILLS "), 50, 0);
		STATS::STAT_SET_INT(rage::joaat("MP0_AWD_20_KILLS_MELEE"), 50, 0);
	}
	void unlock_nightclub() {
		char sbuf[50];
		int stat_r;
		STATS::STAT_GET_INT(rage::joaat("MPPLY_LAST_MP_CHAR"), &stat_r, 1);
		snprintf(sbuf, sizeof(sbuf), "MP%i%s", stat_r, "CLUB_POPULARITY");
		STATS::STAT_SET_INT(rage::joaat(sbuf), 1000, 1);
	}
}

namespace big::menu
{
	void network_recovery_unlocks_menu::menu()
	{
		using namespace ui;

		m_renderer.new_sub<sub>("Unlocks", SubRecoveryUnlocks, [](sub* core)
			{
				m_renderer.m_enable_player_info = false;
				core->add_option<simple_option>(XOR("Unlock All"), nullptr, [] {
					recovery::unlock_all();
					});
				core->add_option<simple_option>(XOR("Tattoos"), nullptr, [] {
					recovery::unlock_tattoo();
					});
				core->add_option<simple_option>(XOR("Clothing"), nullptr, [] {
					recovery::unlock_clothing();
					});
				core->add_option<simple_option>(XOR("Weapon"), nullptr, [] {
					recovery::unlock_weapons();
					});
				core->add_option<simple_option>(XOR("Stats"), nullptr, [] {
					recovery::unlock_stats();
					});
				core->add_option<simple_option>(XOR("Lsc Customs"), nullptr, [] {
					recovery::unlock_lsc();
					});
				core->add_option<simple_option>(XOR("Club Popularity"), nullptr, [] {
					recovery::unlock_nightclub();
					});
			});
	}

	void network_recovery_unlocks_menu::script_init() {}

	void network_recovery_unlocks_menu::script_on_tick() {}

	void network_recovery_unlocks_menu::script_func()
	{
		m_network_recovery_unlocks_menu.script_init();
		while (true)
		{
			m_network_recovery_unlocks_menu.script_on_tick();
			script::get_current()->yield();
		}
	}
}